### PR TITLE
Upgrade PyNaCl to 1.2.1

### PR DESCRIPTION
**Pull request by sfstpala**

### CODE REVIEW

**Comment by sfstpala** [comment]
done :)

**Comment by sfstpala** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

9eXuS08PYutBy5018MA6fq8v7jyInU1TfWyYWupgTPTWhBsKC1fWcLLXY2vHG5Q

END BLOCK

**Comment by ttmc** [comment]
Thanks @sfstpala 

This PR looks okay to me, and all the tests are passing, but I'd like @muawiakh to take a look at it before we mere it.

**Comment by muawiakh** [comment]
@sfstpala why do we need to update this package though? Why is this necessary?

**Comment by ttmc** [comment]
@sfstpala I created a new version of the `cryptoconditions` package which includes your change, it's version 0.7.3: https://pypi.org/project/cryptoconditions/0.7.3/

**Pull request merged**
