### PR TITLE
Fixing default encoding for seed in generating Ed25519 keypair

### PR DESCRIPTION
**Pull request by excerebrose**

### CODE REVIEW

**Comment by ttmc** [comment]
The line in question now reads:

`return cls(nacl.signing.SigningKey(seed, 'bytes').encode(encoder=Base58Encoder))`

Does that mean `seed` should be a Python bytes object? Could you add a docstring to the `generate_with_seed` method just to make it clear?

**Comment by excerebrose** [comment]
Yup, the method docstring already has that incorporated - 
```
   Generate a new key pair.

    Args:
        seed (bytes): 32-byte seed for deterministic generation.
    Returns:
        A tuple of (private_key, public_key) encoded in base58.
```

**Comment by ttmc** [comment]
Okay, I will merge this PR, but I don't know how important this change is.

Do you think we should make another release of the `cryptoconditions` package because of it?

**Comment by ttmc** [comment]
My guess is that if you passed something that was a `str` object (i.e. bytes encoded via base58) and not a bytes object, then there would be an exception.

**Comment by excerebrose** [comment]
Just noticed an exception being thrown, I have reverted the merge and will reopen this once its fixed.

**Pull request merged**
